model_type: language

logger:
    path: /home/dml/speech_recognition/dataset/logs/all_lng_rnn.logs
    level: 20

params_path: # None
net_info:
    net_name: multi_rnn
    net_cfg:
        seq_len: 48
        cell_type: bilstm
        num_hiddens: [128, 256, 2882]

train_cfg:
    context: [gpu, [5]]
    train_iter:
        list_path: /home/dml/speech_recognition/dataset/fbank_thchs30/list_files/train.lst
        input_depth: 1208
        seq_len: 48
        py_to_idx_path: /home/dml/speech_recognition/dataset/fbank_thchs30/dict/pinyins_to_index.json
        ch_to_idx_path: /home/dml/speech_recognition/dataset/fbank_thchs30/dict/characters_to_index.json
        batch_size: 128
        shuffle: True
        num_workers: 4
    valid_iter:
        list_path: /home/dml/speech_recognition/dataset/fbank_thchs30/list_files/valid.lst
        input_depth: 1208
        seq_len: 48
        py_to_idx_path: /home/dml/speech_recognition/dataset/fbank_thchs30/dict/pinyins_to_index.json
        ch_to_idx_path: /home/dml/speech_recognition/dataset/fbank_thchs30/dict/characters_to_index.json
        batch_size: 128
        shuffle: False
        num_workers: 4
    metric:
        phase: train
    optimizer:
        name: adam
        config:
            learning_rate: 0.0001
            wd: 0.0005
            rescale_grad: 1
    batch_end_callback:
        frequent: 1
    epoch_end_callback:
        checkpoint_prefix: /home/dml/speech_recognition/model/all_lng_rnn
        criteria_name: acc
        rule: greater
        lr_factor: 0.5
        thresh: 10
    epoch: 200
    early_stop: 20
    data_names: [data]
    label_names: [label]
