model_type: language

logger:
    path: /home/dengmengling/Public/log/lng_cbhg.logs
    level: 20

params_path: # None
net_info:
    net_name: cbhg
    net_cfg:
        seq_len: 48
        input_cls: 1208
        output_cls: 2882

train_cfg:
    context: [cpu, [0]]
    train_iter:
        list_path: /home/dengmengling/Public/thchs30_fbank/list_files/train.lst
        input_depth: 1208
        seq_len: 48
        py_to_idx_path: /home/dengmengling/Public/thchs30_fbank/dict/pinyins_to_index.json
        ch_to_idx_path: /home/dengmengling/Public/thchs30_fbank/dict/characters_to_index.json
        batch_size: 64
        shuffle: True
        num_workers: 4
    valid_iter:
        list_path: /home/dengmengling/Public/thchs30_fbank/list_files/valid.lst
        input_depth: 1208
        seq_len: 48
        py_to_idx_path: /home/dengmengling/Public/thchs30_fbank/dict/pinyins_to_index.json
        ch_to_idx_path: /home/dengmengling/Public/thchs30_fbank/dict/characters_to_index.json
        batch_size: 64
        shuffle: False
        num_workers: 4
    metric:
        phase: train
    optimizer:
        name: adam
        config:
            learning_rate: 0.0008
            wd: 0.0005
            rescale_grad: 1
    batch_end_callback:
        frequent: 1
    epoch_end_callback:
        checkpoint_prefix: /home/dml/speech_recognition/model/lng_cbhg
        criteria_name: acc
        rule: greater
        lr_factor: 0.5
        thresh: 10
    epoch: 200
    early_stop: 20
    data_names: [data]
    label_names: [label]
